TEMPLATE_INPUT: 
  Folder : ./input/
  Input_template_file_name : trialInformation_soybeanBM_y22.csv

COLUMNS_TEMPLATE:
  - Plot
  - Rep

NEW_COLUMNS:
  Experiment : ACRE-Biomass
  Season : y22
  Environment : Early planting date
  Measurement : trifoliate leaf dry weight
  Sampling_identifier : Sampling-5

SAMPLES_PER_PLOT:
  Sample_name: 
    - A
    - B
    - C
    - D

SAMPLE_IDENTIFIER :
  id_sample:
    - Plot
    - Sample_name
    - Experiment
    - Environment
    - Season
    - Measurement
    - Sampling_identifier

TEMPLATE_OUTPUT: 
  - Measurement
  - Sampling_identifier
  - Experiment
  - Environment
  - Season

  